/**
 * Rick and Morty API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CharacterListResponseInfo { 
    /**
     * The total number of characters.
     */
    count?: number;
    /**
     * The total number of pages.
     */
    pages?: number;
    /**
     * URL of the next page.
     */
    next?: string | null;
    /**
     * URL of the previous page.
     */
    prev?: string | null;
}

