/**
 * Rick and Morty API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CharacterOrigin { 
    /**
     * The name of the character\'s origin location.
     */
    name?: string;
    /**
     * Link to the character\'s origin location.
     */
    url?: string;
}

