/**
 * Rick and Morty API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Character } from './character';
import { CharacterListResponseInfo } from './characterListResponseInfo';


export interface CharacterListResponse { 
    info?: CharacterListResponseInfo;
    results?: Array<Character>;
}

